apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-ecomm
  labels:
    app: frontend-ecomm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-ecomm
  template:
    metadata:
      labels:
        app: frontend-ecomm
    spec:
      containers:
      - name: frontend-ecomm
        image: ephrash1/frontend-ecomm:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-ecomm-service
spec:
  type: LoadBalancer
  selector:
    app: frontend-ecomm
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
